import Footer from "./_components/Footer";
import "./globals.css";

export const metadata = {
  title: "Echo Vault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="fixed top-0 z-[-2] h-screen w-screen bg-[#0D0A1C] bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(123,97,255,0.3),rgba(255,255,255,0))]"></div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
